#!/bin/bash

release_file=/etc/os-release
logfile=/var/log/upgrader.log
errorlog=/var/log/upgrader-errors.log

check_exit_status() {
  if [ $? -ne 0 ]
  then
    echo "An error occurred, please check the $errorlog file."
  fi
}

if grep -q "Arch" $release_file
then
  # The host is based on Arch, run the pacman update command
  sudo pacman -Syu 1>>$logfile 2>>$errorlog
  check_exit_status
fi

if grep -q "Pop" $release_file || grep -q "Ubuntu" $release_file
then
  # The host is based on Ubuntu,
  # Run the apt version of the command
  sudo apt update 1>>$logfile 2>>$errorlog
  check_exit_status

  sudo apt dist-upgrade -y 1>>$logfile 2>>$errorlog
  check_exit_status
fi
